# Generated by Django 4.1.7 on 2023-03-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=20)),
                ('img_url', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20)),
                ('memory', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
            ],
        ),
    ]
