# Generated by Django 4.1.7 on 2023-03-11 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_smartphone_img_url_alter_smartphone_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartphone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='memory',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ram',
            field=models.IntegerField(),
        ),
    ]
