# Generated by Django 4.1.7 on 2023-03-10 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_smartphone_img_url_alter_smartphone_memory'),
        ('api', '0003_alter_smartphone_price'),
    ]

    operations = [
    ]
