# Generated by Django 4.1.7 on 2023-03-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20230310_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='memory',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='model',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
